In [1]:
import torch 
import numpy as np
import pandas as pd

In [2]:
torch.__version__

'1.5.1'

In [3]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [7]:
#vector
vector = torch.tensor([1,2,4])
vector

tensor([1, 2, 4])

In [8]:
vector.ndim #count the number of sqaure brackets to get ndim (one side)

1

In [10]:
#matrix
matrix = torch.tensor([[1,2],[2,3]])
matrix

tensor([[1, 2],
        [2, 3]])

In [12]:
#lets guess the ndim , it must be 2
matrix.ndim

2

In [13]:
matrix.shape

torch.Size([2, 2])

In [14]:
#tensor

Tensor = torch.tensor([[[1,2],[2,3],[3,4]]])
Tensor

tensor([[[1, 2],
         [2, 3],
         [3, 4]]])

In [15]:
#ndim must be 3
Tensor.ndim

3

In [16]:
#shape has to be 1,3,2
Tensor.shape

torch.Size([1, 3, 2])

# Random

In [17]:
torch.rand(size = (1,2))

tensor([[0.9005, 0.7664]])

In [18]:
torch.rand(size = (1,2,2))

tensor([[[0.5672, 0.2548],
         [0.6411, 0.7055]]])

In [19]:
torch.rand(size = (1,2,2),dtype=float)

tensor([[[0.2578, 0.1805],
         [0.0747, 0.4113]]], dtype=torch.float64)

In [34]:
#torch.rand(size = (1,2,2),dtype=torch.int8)
torch.randint(low=0,high = 10,size = (1,2))

tensor([[8, 9]])

# Zeros and ones

In [39]:
torch.zeros((2,3)).dtype

torch.float32

In [40]:
torch.ones((2,3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])

# creating range

In [42]:
torch.arange(1,10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
torch.arange(1,10,2)

tensor([1, 3, 5, 7, 9])

# Basic operations

In [47]:
Tensor = torch.Tensor([1,2,4,4])
Tensor + 10

tensor([11., 12., 14., 14.])

In [48]:
Tensor - 10

tensor([-9., -8., -6., -6.])

In [49]:
Tensor * 10

tensor([10., 20., 40., 40.])

In [50]:
Tensor / 10

tensor([0.1000, 0.2000, 0.4000, 0.4000])

In [51]:
torch.add(Tensor,10)

tensor([11., 12., 14., 14.])

In [52]:
torch.mul(Tensor,10)

tensor([10., 20., 40., 40.])

In [53]:
torch.sub(Tensor,10)

tensor([-9., -8., -6., -6.])

In [54]:
a = torch.tensor([1,2,3])
b = torch.tensor([3,4,5])
a+b

tensor([4, 6, 8])

In [55]:
a*b#element wise mul

tensor([ 3,  8, 15])

In [58]:
#matrix mutliplication
a@b #3+8+15

tensor(26)

In [59]:
a.shape,b.shape

(torch.Size([3]), torch.Size([3]))

In [61]:
a = torch.tensor([[1,2],[2,4],[2,2]])
b = torch.tensor([[1,2],[2,2],[1,1]])
a@b #size doent match 

RuntimeError: size mismatch, m1: [3 x 2], m2: [3 x 2] at C:\cb\pytorch_1000000000000\work\aten\src\TH/generic/THTensorMath.cpp:41

In [67]:

a.T @ b 

tensor([[ 7,  8],
        [12, 14]])

In [65]:
torch.matmul(a.T,b)

tensor([[ 7,  8],
        [12, 14]])

In [68]:
tensor_A = torch.tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [70]:
tensor_A,tensor_A.shape

(tensor([[1., 2.],
         [3., 4.],
         [5., 6.]]),
 torch.Size([3, 2]))

# Linear model  : y = mx+c

In [75]:
linear = torch.nn.Linear(in_features=2,out_features=1)
output = linear(tensor_A)
output

tensor([[-0.0254],
        [ 0.0043],
        [ 0.0341]], grad_fn=<AddmmBackward>)

In [73]:
output.shape

torch.Size([3, 4])

In [76]:
x = torch.tensor([1,2,3,4,5],dtype=float)
torch.min(x),torch.max(x),torch.sum(x),torch.mean(x)

(tensor(1., dtype=torch.float64),
 tensor(5., dtype=torch.float64),
 tensor(15., dtype=torch.float64),
 tensor(3., dtype=torch.float64))

In [77]:
x = torch.tensor([1,2,3,4,5],dtype=float)
torch.argmin(x),torch.argmax(x)

(tensor(0), tensor(4))

# changing datatype


In [79]:
x_int = torch.arange(0,10,2)
x_int

tensor([0, 2, 4, 6, 8])

In [82]:
x_int.type(torch.float16)

tensor([0., 2., 4., 6., 8.], dtype=torch.float16)

# Reshaping, stacking, squeezing and unsqueezing

In [83]:
t = torch.arange(1,10)
t.shape

torch.Size([9])

In [84]:
t.reshape(1,9)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [89]:
t_v = t.view(1,9)
t_v.shape
#view creates  a new veiew of exsiting tensor without affecting original

torch.Size([1, 9])

In [95]:
t_v[0,:1] =111
t_v,t
#it also changed the original tensor

(tensor([[111,   2,   3,   4,   5,   6,   7,   8,   9]]),
 tensor([111,   2,   3,   4,   5,   6,   7,   8,   9]))

In [99]:
t_s = torch.arange(1,6)
t_s,t_s.shape

(tensor([1, 2, 3, 4, 5]), torch.Size([5]))

In [100]:
t_s_1 = torch.stack([t_s]) #default dim=0
t_s_1.shape #vector

torch.Size([1, 5])

In [102]:
t_s_2 = torch.stack([t_s,t_s])
t_s_2.shape,t_s_2  #matix of size 2, 5

(torch.Size([2, 5]),
 tensor([[1, 2, 3, 4, 5],
         [1, 2, 3, 4, 5]]))

In [103]:
t_s_3 = torch.stack([t_s,t_s,t_s])
t_s_3.shape,t_s_3 #matrix of size 3,5

(torch.Size([3, 5]),
 tensor([[1, 2, 3, 4, 5],
         [1, 2, 3, 4, 5],
         [1, 2, 3, 4, 5]]))

In [105]:
t_s_1 = torch.stack([t_s],dim=1) #default dim=0
t_s_1.shape,t_s_1 #vector

(torch.Size([5, 1]),
 tensor([[1],
         [2],
         [3],
         [4],
         [5]]))

In [107]:
t_s_1 = torch.stack([t_s,t_s],dim=1) #default dim=0
t_s_1.shape,t_s_1 #vector

(torch.Size([5, 2]),
 tensor([[1, 1],
         [2, 2],
         [3, 3],
         [4, 4],
         [5, 5]]))

In [108]:
t_sq = torch.tensor([[1,2],[3,4]])
t_sq.shape,t_sq

(torch.Size([2, 2]),
 tensor([[1, 2],
         [3, 4]]))

In [114]:
t_sq.squeeze(dim=0)

tensor([[1, 2],
        [3, 4]])

In [120]:
torch.tensor([[1,2,3,4]]).shape
torch.tensor([[1,2,3,4]]).squeeze().shape

torch.Size([4])

# GPU's

In [121]:
!nvidia-smi

Thu Mar  9 13:05:54 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 516.40       Driver Version: 516.40       CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0  On |                  N/A |
| N/A   47C    P8     1W /  N/A |    128MiB /  4096MiB |      3%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [122]:
torch.cuda.is_available()

True

In [123]:
device = "cuda" if torch.cuda.is_available() else 'cpu'
device

'cuda'